version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8822:8000
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true